version: "3.7"

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reactive_spring