version: "3.7"

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
    networks:
      - postgres

networks:
  postgres:
    driver: bridge